wget https://www.facebook.com/rsrc.php/v3/y0/r/f1VBM9ZaMw5.png
wget https://www.facebook.com/rsrc.php/v3/y3/r/c3CNAfMUGru.png
wget https://www.facebook.com/rsrc.php/v3/y4/r/-PAXP-deijE.gif
wget https://www.facebook.com/rsrc.php/v3/y4/r/cj6XtJxjFyq.png
wget https://www.facebook.com/rsrc.php/v3/y5/r/3zcUUUQYjb3.png
wget https://www.facebook.com/rsrc.php/v3/y6/r/KRjqUzVfNrc.png
wget https://www.facebook.com/rsrc.php/v3/y9/r/6K8v8Ju8kL2.png
wget https://www.facebook.com/rsrc.php/v3/yA/r/KgMjNNPJc5W.png
wget https://www.facebook.com/rsrc.php/v3/yC/r/wzjc71CPBlw.png
wget https://www.facebook.com/rsrc.php/v3/yD/r/t-wz8gw1xG1.png
wget https://www.facebook.com/rsrc.php/v3/yF/r/GtWy2MKJqwZ.png
wget https://www.facebook.com/rsrc.php/v3/yG/r/RozqvGf0LV-.gif
wget https://www.facebook.com/rsrc.php/v3/yH/r/oyO8OjcaqSp.png
wget https://www.facebook.com/rsrc.php/v3/yJ/r/GeDnuL6fruy.png
wget https://www.facebook.com/rsrc.php/v3/yJ/r/_xLB5kZsJ63.png
wget https://www.facebook.com/rsrc.php/v3/yM/r/NBYvgFic_Jk.png
wget https://www.facebook.com/rsrc.php/v3/yN/r/lhltfEJTTYj.png
wget https://www.facebook.com/rsrc.php/v3/yO/r/kWjQESU8aJV.png
wget https://www.facebook.com/rsrc.php/v3/yU/r/n93MoBZD7fU.png
wget https://www.facebook.com/rsrc.php/v3/yV/r/uLWLA1lWkEx.png
wget https://www.facebook.com/rsrc.php/v3/yW/r/-8uKO6LFsOx.png
wget https://www.facebook.com/rsrc.php/v3/yW/r/Cg43IrsPc7P.png
wget https://www.facebook.com/rsrc.php/v3/yY/r/2lbMzJ3my2D.png
wget https://www.facebook.com/rsrc.php/v3/yY/r/95mP3iqAHQG.png
wget https://www.facebook.com/rsrc.php/v3/yZ/r/3Qthvek6kqx.gif
wget https://www.facebook.com/rsrc.php/v3/yc/r/K_BrTiD28l1.png
wget https://www.facebook.com/rsrc.php/v3/ym/r/KRk8EehrpjO.png
wget https://www.facebook.com/rsrc.php/v3/yt/r/D47CF9k_yA8.png
wget https://www.facebook.com/rsrc.php/v3/yu/r/YMjpKfMrD6I.png
wget https://www.facebook.com/rsrc.php/v3/yu/r/yTtSEFbxIMr.png
wget https://www.facebook.com/rsrc.php/v3/yv/r/tjvhMulZ-W8.png
wget https://www.facebook.com/rsrc.php/v3/yv/r/tlQgBHy1WZ9.png
wget https://www.facebook.com/rsrc.php/v3/yw/r/drP8vlvSl_8.gif
wget https://www.facebook.com/rsrc.php/v3/yw/r/iiy40TSF95R.png
